name: rnote_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  image_picker: ^0.8.5+3
  flutter_dotenv: ^5.0.2
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  json_annotation: ^4.6.0
  image: ^3.2.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - .env
    - rnote-355708-a04964504799.json
